baseTrie.js
checkpoint-interface.js
readStream.js

easier to understand
nodeRef is either a hash or a rawNode, depending on how the node is stored in the trie

walkTrie - rename 'root' arg to 'nodeRef'

---

baseTrie.js

This PR fix the test designed here:
https://github.com/ethereum/tests/pull/125

Fix insert a node in the middle leaf

---

baseTrie.js
prioritizedTaskExecutor.js
test/prioritizedTaskExecutor.js

Fix for https://github.com/ethereumjs/merkle-patricia-tree/issues/36
The root cause of the issue is the trie is traversed asynchronously, in such a way that nodes on different levels are explored with equal probability, resembling breadth-first search. This requires the bulk of the trie to be loaded into memory before any entries can be emitted by the stream.
This pull request adds `PrioritizedTaskExecutor` with a pool and a priority queue, node lookups are prioritised by node key length. This resembles depth-first search, which solves the issue.
Also tested here https://github.com/medvedev1088/merkle-patricia-tree/pull/1
New code is covered in `test/prioritizedTaskExecutor.js` but coverage only picks `test/index.js`

Fix OutOfMemory in read stream

---

checkpoint-interface.js

This fixes part of the issues described in https://github.com/trufflesuite/ganache-cli/issues/417.
The `asyncFirstSeries` function called inside `Trie#getRaw` was iterating over an array that could be mutated by the checkpoint `_enterCpMode`/`_exitCpMode ` functions, causing the familiar `TypeError: Cannot read property 'get' of undefined`.
I replaced the mutations with reassignments.
Note that the tests written in https://github.com/trufflesuite/ganache-core/pull/41 still fail, now both with the same error: `TypeError: Cannot read property 'pop' of undefined`.

Fix race condition due to mutated _getDBs/_putDBs

---

checkpoint-interface.js
index.js

`_scratch` was leaking because `checkpointInterface` was called without assigning `this` (in strict mode it would fail because `this` would be undefined, otherwise it takes global/window as 'this', hence the leak)
I'm not familiar with tape, if there's an option to check leaks (like --check-leaks in mocha) it would be great to use - it will never happen again in the future. I didn't find something similar to that in tape.
```javascript
function checkpointInterface (trie) {
this._scratch = null // before the fix `this` may be global, window or undefined
// ...
}
```

fix _scratch 'leak' to global/window

---

package.json

This PR fixes the coverage report, which appeared to only be running for tests under index.js.

Fix coverage to run all scripts under tape

---

dist/trie.js
proof.js
test/proof.js

This PR fixes a bug in verify proof where "Error: Unexpected end of proof" if the tree contains an extension node with an embedded branch node. 
A simple example of this bug is below:
```javascript
const Tree = require('merkle-patricia-tree');
const tree = new Tree();
tree.put('a', 'a', (err) => {
tree.put('b', 'b', (err) => {
Tree.prove(tree, 'a', (err, proof) => {
Tree.verifyProof(tree.root, 'a', proof, (err, val) => {
// err = "Error: Unexpected end of proof"
// expected : val === 'a' 
}
} 
}
}
```
Fixes #52.

Fix bug in verifyProof

---

.travis.yml
README.md
baseTrie.js
checkpoint-interface.js
dist/trie.js
package.json

See: https://github.com/ethereumjs/ethereumjs-client/issues/53
The current versions of the levelup, memdown and level-ws modules are very old. This PR replaces these with modern and up-to-date versions. There were some minor breaking API changes with the new versions so some code had to be modified.
Also, the newer versions of the level modules only support node 6 and higher.
All tests are passing but I'm not sure what the best way to make sure other external dependencies aren't broken. Ideas?

Replace levelup+memdown with level-mem 3.0.1 and upgrade level-ws to 1.0.0

---

.gitignore
docs/index.md
src/baseTrie.js
src/checkpoint-interface.js
src/scratchReadStream.js

The `ScratchReadStream` class was being defined within `checkpoint-interface.js`. I thought the codebase would be easier to manage if classes were their own separate files, but this is not a necessary change and I'm happy to revert that.

 Rewrite baseTrie as an ES6 class. Extract scratchReadStream to its own file from checkpoint-interface

---

src/secure.js
test/secure.js

`SecureTrie` hashes keys before `put` and `get`, however because it inherited `CheckpointTrie`'s `prove` and `verifyProof` methods (which doesn't hash keys), the methods didn't work because they couldn't find nodes in the trie. This PR fixes that and adds a simple test case which fails without the fix but passes afterwards.

Fix prove and verifyProof in SecureTrie

---

.gitignore
src/baseTrie.js
test/index.js
test/secure.js

PR #82 broken into 2 pieces
This one doesn't deal with proofs. It just standardizes the callback pattern of `_lookupNode`

_lookupNode callback to use standard error, response pattern

---

src/util/hex.js
src/util/nibbles.js

I remember facing some issues with the ES6 `export` syntax and it revolved around browsers. I suggest we use `module.exports` for now like the rest of the library. We can go back to the cleaner `export` syntax during the Typescript migration.

Use module.exports syntax in util files

---

docs/index.md
src/baseTrie.js
src/checkpointTrie.js
src/secure.js

**tl;dr** Changes since the `v3.0.0` release had introduced breaking changes (and bugs). This PR makes those changes backwards compatible, and fixes the bugs. `ethereumjs-vm` passes all tests without any modifications after integrating this PR.
The changes are:
- Re-introduce `getRaw`, `putRaw`, `delRaw` methods (but mark them as deprecated)
- Instead of a `DB` object, instantiate the trie via a leveldb object (like before). This necessitated some other changes in `checkpointTrie` and `secureTrie`.
- Fixed a bug in `CheckpointTrie._exitCpMode` which passed the wrong object to `WriteStream`
- The first two changes created a (difficult to track) bug: `SecureTrie.copy` would copy `CheckpointTrie`'s scratch db and use that as the underlying database, which meant the actual state data wasn't …

Re-add raw methods, accept leveldb in constructor, minor fixes

---

docs/index.md

I ran `npm run build:docs` because the links to the source code were broken (there was a colon before "ethereumjs" --> https://git@github.com/:ethereumjs/merkle-patricia-tree/blob/88e1a25df6ec3cb591ed2c7e78d00788d8adf60f/src/secure.js#L12-L55)

fixed src code links in docs

---

package.json
src/baseTrie.ts
src/checkpointTrie.ts
src/db.ts
src/secure.ts
src/trieNode.ts
src/types.ts

On a high-level this PR:
- Adds typedefs for leveldb
- Breaks `TrieNode` into 3 classes `BranchNode`, `ExtensionNode` and `LeafNode`. It also makes the necessary modifications in `BaseTrie` to make it work with this new structure.
I'm still not fully sure about the details of the new types, specially around `EmbeddedNode`. That might have to change.
The way some of the internal methods modify nodes is very prone to errors (I had to debug a really nasty bug), due to arrays being mutable references.
I think after this I will try to promisify some parts and make the code a bit flatter so it's easier to work with.
Update: Oh and I tested it against ethereumjs-vm, tests pass.

Refactor TrieNode, add levelup types

---

src/baseTrie.ts
src/checkpointTrie.ts
test/index.spec.ts

This PR:
* Adds typedoc for `_formatNode` and `_walkTrie`
* Fixes typos `extention` => `extension`
---
While refactoring I found that `_formatNode` has a parameter `remove` that is not being utilized inside the method in `baseTrie.ts` but is being used in `checkpointTrie.ts`. It is called with the value being `true` in two cases: [here](https://github.com/ethereumjs/merkle-patricia-tree/blob/41ef2d8e5dc2c7824cc3e7f8eaa4577405fb2b38/src/baseTrie.ts#L378) and [here](https://github.com/ethereumjs/merkle-patricia-tree/blob/41ef2d8e5dc2c7824cc3e7f8eaa4577405fb2b38/src/baseTrie.ts#L611).
In its [history](https://github.com/ethereumjs/merkle-patricia-tree/blob/v2.3.0/baseTrie.js#L680), the `remove` parameter was used alongside `if (this.isCheckpoint)` on whether to remove the node by pushing a …

Better document `_formatNode`

---

docs/classes/_basetrie_.trie.md
docs/classes/_checkpointtrie_.checkpointtrie.md
docs/classes/_secure_.securetrie.md
src/baseTrie.ts
src/checkpointTrie.ts
src/util/hex.ts
src/util/nibbles.ts

This PR clarifies some types from `number[]` to `Nibbles` for better readability.

Use `Nibbles` type for `number[]`

---

package.json
src/util/hex.ts

This PR upgrades dependency `ethereumjs-util` to `7.0.0`.

Upgrade ethereumjs-util to 7.0.0 / Upgrade level-mem to 5.0.1

---

.gitignore
.prettierignore
package.json
tsconfig.browser.json
tsconfig.json
tsconfig.prod.json

@sz-piotr and @msieczko suggested to use a ES2017 build for the performance benefit of not using ts generators for async code.
@alcuadrado highlighted the importance of maintaining browser support and suggested using the [`browser`](https://docs.npmjs.com/files/package.json#browser) field in `package.json`.
This PR makes `dist` a ES2017 build and adds an additional build at `dist.browser` for ES5 (as inspired by [this post](https://medium.com/collaborne-engineering/typescript-create-library-for-nodejs-and-browser-fece291d517f)).

Create dual ES5 and ES2017 builds

---

CHANGELOG.md
src/checkpointTrie.ts
src/secure.ts
test/secure.spec.ts

This PR is a **breaking change** that by default includes checkpoint metadata in copying a SecureTrie.
See [this comment](https://github.com/ethereumjs/merkle-patricia-tree/pull/118#issuecomment-632050186) for some more context. 
In ethereumjs-vm, `SecureTrie.copy` has been used with the assumption that checkpointing state is *not* copied, so dependent libraries will have to update accordingly. This PR adds the param `includeCheckpoints` to `SecureTrie.copy` (identical to `CheckpointTrie.copy`) so passing `false` can maintain original behavior.
Thanks to @msieczko and @s1na for their insights.

Include checkpoints by default in SecureTrie.copy

---

CHANGELOG.md
README.md
docs/classes/_basetrie_.trie.md
docs/classes/_checkpointtrie_.checkpointtrie.md
docs/classes/_secure_.securetrie.md
docs/modules/_basetrie_.md
package.json
src/baseTrie.ts
src/checkpointTrie.ts
src/db.ts
src/secure.ts
src/util/hex.ts
src/util/nibbles.ts
test/proof.spec.ts
test/secure.spec.ts
tsconfig.json
typedoc.json

This PR:
* Renames `prove` to `createProof`
* Keeps `prove` as a deprecated alias
* Introduces `type Proof = Buffer[]` to improve param types for `fromProof`, `createProof`, and `verifyProof`. 
Fixes #120
This PR also tidies up and adds some missing doc comments. In particular `@memberof` `@method` and `@returns {Promise}` are automatically understood so they don't need to be explicitly defined (see [Doc Comments syntax](https://typedoc.org/guides/doccomments/)).

Rename Trie.prove to Trie.createProof

---

CHANGELOG.md
README.md
docs/classes/_basetrie_.trie.md
docs/classes/_checkpointtrie_.checkpointtrie.md
docs/classes/_secure_.securetrie.md
docs/modules/_basetrie_.md
package.json
src/baseTrie.ts
src/checkpointTrie.ts
src/db.ts
src/secure.ts
src/util/hex.ts
src/util/nibbles.ts
test/proof.spec.ts
test/secure.spec.ts
tsconfig.browser.json
tsconfig.json
tsconfig.prod.json
typedoc.json

This release introduces a major API upgrade from callbacks to Promises.
Example using async/await syntax:
```typescript
import { BaseTrie as Trie } from 'merkle-patricia-tree'
const trie = new Trie()
async function test() {
await trie.put(Buffer.from('test'), Buffer.from('one'))
const value = await trie.get(Buffer.from('test'))
console.log(value.toString()) // 'one'
}
test()
```
See the [docs](https://github.com/ethereumjs/merkle-patricia-tree/tree/master/docs) for the latest Promise-based method signatures.
To clarify the method's purpose `Trie.prove` has been renamed to `Trie.createProof`. `Trie.prove` has been deprecated but will remain as an alias for `Trie.createProof` until removed.
`getRaw`, `putRaw` and `delRaw` were deprecated in `v3.0.0` and have been removed from this release. …

Release - v4.0.0

---

README.md

Added the [Merkle Patricia Trees tutorial](https://github.com/gabrocheleau/merkle-patricia-trees-examples) to the documentation, deleted the blog post with a 404 error and added a note for the blog post with outdated code.

Update readme references and examples

---

docs/classes/_basetrie_.trie.md
docs/classes/_checkpointtrie_.checkpointtrie.md
docs/classes/_secure_.securetrie.md
src/baseTrie.ts
src/checkpointTrie.ts
src/db.ts
src/prioritizedTaskExecutor.ts
src/secure.ts
src/util/hex.ts
src/util/nibbles.ts

This PR targets to make the `BaseTrie` code from MPT more readable and do some basic clean up.
Following changes:
- Improved constructor documentation
- Removed redundant @param type documentation on all files
- Made `Trie.setRoot()` private
- Reordering of `BaseTrie` functionality to get to more intuitive function clusters
- Various code doc additions
- Explicitly defined (so: not inlined) onFound functions in Trie for better code readability
- Documentation rebuild
It might be easiest to review this PR by going along commit-by-commit.

Base trie code documentation and function clustering

---

src/baseTrie.ts
src/checkpointTrie.ts

This PR fixes the double-execution of Node serialization in CheckpointTrie._formatNode() as well as moves a unified `_formatNode()` to `BaseTrie` (the added somewhat dummy `isCheckpoint()` getter there avoids a TypeScript error) to remove redundancy.
This gives a significant performance increase when running the checkpointing benchmarks:
Run on PR:
```shell
$ ts-node benchmarks/checkpointing.ts && ts-node benchmarks/checkpointing.ts && ts-node benchmarks/checkpointing.ts && ts-node benchmarks/checkpointing.ts && ts-node benchmarks/checkpointing.ts
benchmarks/checkpointing.ts | average execution time: 0s 148.515ms
benchmarks/checkpointing.ts | average execution time: 0s 146.228ms
benchmarks/checkpointing.ts | average execution time: 0s 150.828ms
benchmarks/checkpointing.ts | average …
```

Fix double serialize in CheckpointTrie._formatNode()

---

.gitignore
README.md
benchmarks/checkpointing.ts
benchmarks/random.ts
package.json

Hi @alcuadrado, I thought it would be the most sustainable option to create a PR on your request to send the MPT flamegraph, especially since sending around an HTML flamegraph is a bit tricky.
The PR integrates basic profiling on the library, I also updated the `random.ts` benchmark a bit, this was actually already quite similar before in comparison to my code I had for profiling.
This PR is of course just one small step to first-introduce this basic profiling here. Everyone feel free to change on everything on subsequent PRs. Once this is merged it should be easily doable to generate a flamegraph with:
```shell
npm run profiling
```

Add simple profiling / Basic benchmark & README update

---

.eslintrc.js
.github/workflows/build.yml
benchmarks/checkpointing.ts
benchmarks/random.ts
karma.conf.js
package.json
prettier.config.js
src/baseTrie.ts
src/checkpointTrie.ts
src/db.ts
src/trieNode.ts
src/util/nibbles.ts
test/checkpoint.spec.ts
test/db.spec.ts
test/encoding.spec.ts
test/index.spec.ts
test/official.spec.ts
test/prioritizedTaskExecutor.spec.ts
test/proof.spec.ts
test/scratch.spec.ts
test/secure.spec.ts
test/stream.spec.ts
tsconfig.benchmarks.json
tsconfig.prod.json
tslint.json

This PR upgrades to the `ethereumjs-config` 2.0 libs and fixes the new lint issues.

Upgrade to ethereumjs-config 2.0 libs

---

CHANGELOG.md
benchmarks/checkpointing.ts
benchmarks/random.ts
docs/README.md
docs/classes/_basetrie_.trie.md
docs/classes/_checkpointtrie_.checkpointtrie.md
docs/classes/_secure_.securetrie.md
docs/classes/_util_walkcontroller_.walkcontroller.md
docs/modules/_basetrie_.md
docs/modules/_util_walkcontroller_.md
src/baseTrie.ts
src/checkpointTrie.ts
src/index.ts
src/prioritizedTaskExecutor.ts
src/readStream.ts
src/scratch.ts
src/scratchReadStream.ts
src/secure.ts
src/util/walkController.ts
src/util/walkStrategy.ts
test/index.spec.ts
test/prioritizedTaskExecutor.spec.ts
typedoc.json

Related: #131 
This introduces a `WalkStrategy` object, which is responsible for handling the event queue. Consumers of this class are themselves responsible for adding events to the queue. 
It adds three queuing methods: one to just put a specific node in the queue: `pushNode(nodeRef: Buffer, key: Nibbles = [], priority?: number)`, one to only add a certain branch of a `BranchNode` into the queue: `onlyBranchIndex(node: TrieNode, key: Nibbles = [], childIndex: number, priority?: number)` and one to add all children to the event queue: `allChildren(node: TrieNode, key: Nibbles = []) `. 
The logic itself is mostly based upon the original logic, but now it is stripped down in what I think is a much more readable fashion.
Have to check a few gotcha's here, write some better docs and also see …

Refactor WalkTrie
